### ISSUE TITLE
StateMismatch at /slack/login/ State mismatch upon authorization completion. Try new request.

### ISSUE THREAD

**Issue by dmilleravid** [izdi/django-slack-oauth#10]
Slack asked me to update my app's scopes, which I did. I added the new scopes in the SLACK_SCOPE variables in my Settings file. I tested it in my development environment successfully and was able to OAuth to Slack.

When I pushed my code to production, I get this error message:

> Internal Server Error: /slack/login/
> StateMismatch at /slack/login/ State mismatch upon authorization completion. Try new request.

How can I resolve this? Anyone else having the issue?

---

Here is the full Traceback:

Traceback:

File “/opt/Envs/hardhill-env/local/lib/python2.7/site-packages/django/core/handlers/base.py” in get_response
1. ```
                   response = self.process_exception_by_middleware(e, request)
   ```
   
   File “/opt/Envs/hardhill-env/local/lib/python2.7/site-packages/django/core/handlers/base.py” in get_response
2. ```
                   response = wrapped_callback(request, *callback_args, **callback_kwargs)
   ```
   
   File “/opt/Envs/hardhill-env/local/lib/python2.7/site-packages/django/views/generic/base.py” in view
3. ```
           return self.dispatch(request, *args, **kwargs)
   ```
   
   File “/opt/Envs/hardhill-env/local/lib/python2.7/site-packages/django/utils/decorators.py” in _wrapper
4. ```
           return bound_func(*args, **kwargs)
   ```
   
   File “/opt/Envs/hardhill-env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py” in _wrapped_view
5. ```
               return view_func(request, *args, **kwargs)
   ```
   
   File “/opt/Envs/hardhill-env/local/lib/python2.7/site-packages/django/utils/decorators.py” in bound_func
6. ```
               return func.__get__(self, type(self))(*args2, **kwargs2)
   ```
   
   File “/opt/Envs/hardhill-env/local/lib/python2.7/site-packages/django_slack_oauth/views.py” in dispatch
7. ```
       return super(SlackAuthView, self).dispatch(request, *args, **kwargs)
   ```
   
   File “/opt/Envs/hardhill-env/local/lib/python2.7/site-packages/django/views/generic/base.py” in dispatch
8. ```
       return handler(request, *args, **kwargs)
   ```
   
   File “/opt/Envs/hardhill-env/local/lib/python2.7/site-packages/django_slack_oauth/views.py” in get
9. ```
       self.validate_state(request.GET.get('state'))
   ```
   
   File “/opt/Envs/hardhill-env/local/lib/python2.7/site-packages/django_slack_oauth/views.py” in validate_state
10. ```
            raise StateMismatch('State mismatch upon authorization completion.'
    ```
    
    Exception Type: StateMismatch at /slack/login/ Exception Value: State mismatch upon authorization completion. Try new request.

**Comment by izdi** [comment]
Hi, 

Did you set up cache at your settings file ?

**Comment by dmilleravid** [comment]
No I did not. Is that why it's not working? Why would it work in my dev
environment?

On Fri, Mar 18, 2016 at 12:37 PM, Sergey Keller notifications@github.com
wrote:

> Hi,
> 
> Did you set up cache at your settings file ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/izdi/django-slack-oauth/issues/10#issuecomment-198444271

## 

_David Miller_
dmilleravid@gmail.com
(704) 560-6733  mobile

**Comment by izdi** [comment]
Looks like you have cache set up in your dev env and not in your prod, check at README.md p. 4.2 please. 
:octocat:

**Comment by dmilleravid** [comment]
I use a different Settings file for dev and can't find any cache settings
in it so I'm not sure how I would have cache set up in my dev environment.

I'll set it up anyway and see what happens.

On Fri, Mar 18, 2016 at 12:46 PM, Sergey Keller notifications@github.com
wrote:

> Looks like you have cache set up in your dev env and not in your prod,
> check at README.md p. 4.2 please.
> [image: :octocat:]
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/izdi/django-slack-oauth/issues/10#issuecomment-198447218

## 

_David Miller_
dmilleravid@gmail.com
(704) 560-6733  mobile

**Comment by dmilleravid** [comment]
I have no idea why it's not working ... I added Memcached to my local
environment and now I get the same error as on Prod.

Can you send me all the settings I should have in my settings.py file?  For
MIDDLEWARE_CLASSES, CACHES, INSTALLED_APPS, etc.?

I must be missing something extremely simple.

On Fri, Mar 18, 2016 at 1:59 PM, David Miller dmilleravid@gmail.com wrote:

> I use a different Settings file for dev and can't find any cache settings
> in it so I'm not sure how I would have cache set up in my dev environment.
> 
> I'll set it up anyway and see what happens.
> 
> On Fri, Mar 18, 2016 at 12:46 PM, Sergey Keller notifications@github.com
> wrote:
> 
> > Looks like you have cache set up in your dev env and not in your prod,
> > check at README.md p. 4.2 please.
> > [image: :octocat:]
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/izdi/django-slack-oauth/issues/10#issuecomment-198447218
> 
> ## 
> 
> _David Miller_
> dmilleravid@gmail.com
> (704) 560-6733  mobile

## 

_David Miller_
dmilleravid@gmail.com
(704) 560-6733  mobile

**Comment by dmilleravid** [comment]
I got it to work with Redis.

On Fri, Mar 18, 2016 at 2:54 PM, David Miller dmilleravid@gmail.com wrote:

> I have no idea why it's not working ... I added Memcached to my local
> environment and now I get the same error as on Prod.
> 
> Can you send me all the settings I should have in my settings.py file?
> For MIDDLEWARE_CLASSES, CACHES, INSTALLED_APPS, etc.?
> 
> I must be missing something extremely simple.
> 
> On Fri, Mar 18, 2016 at 1:59 PM, David Miller dmilleravid@gmail.com
> wrote:
> 
> > I use a different Settings file for dev and can't find any cache settings
> > in it so I'm not sure how I would have cache set up in my dev environment.
> > 
> > I'll set it up anyway and see what happens.
> > 
> > On Fri, Mar 18, 2016 at 12:46 PM, Sergey Keller <notifications@github.com
> > 
> > > wrote:
> > > 
> > > Looks like you have cache set up in your dev env and not in your prod,
> > > check at README.md p. 4.2 please.
> > > [image: :octocat:]
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/izdi/django-slack-oauth/issues/10#issuecomment-198447218
> > 
> > ## 
> > 
> > _David Miller_
> > dmilleravid@gmail.com
> > (704) 560-6733  mobile
> 
> ## 
> 
> _David Miller_
> dmilleravid@gmail.com
> (704) 560-6733  mobile

## 

_David Miller_
dmilleravid@gmail.com
(704) 560-6733  mobile

**Comment by izdi** [comment]
Did you check memcached daemon is running on prod?
Glad to hear that worked out with redis, closing. If you have any questions feel free to reopen.
:octocat:
