### ISSUE TITLE
Missing initial migrations file.

### ISSUE THREAD

**Issue by avelis** [izdi/django-slack-oauth#2]
For those of us looking to utilize this project. The library does not contain an initial model migration file.

This in turn leaves integration of this library to store our own migration files and map it via migration modules.

**Comment by avelis** [comment]
@izdi :tada: 
Do you know when there could be a PyPi release with this merged change available?

**Comment by izdi** [comment]
@avelis Gonna do this asap :+1:

**Comment by izdi** [comment]
@avelis done, added support for south migration as well

**Comment by avelis** [comment]
@izdi I saw that. Wow, I really appreciate it!

Thank you for also creating this project and maintaining it. Great contribution for the Django community!
