### ISSUE TITLE
Upgrade django-jsonfield version for Django 1.11.2 compatibility

### ISSUE THREAD

**Issue by avelis** [izdi/django-slack-oauth#20]
[djanog-jsonfield recently released version 2.0.2 ](https://github.com/dmkoch/django-jsonfield/releases/tag/2.0.2)which upgrades the libraries compatibility with Django v1.11.2 . Discussion on the issue can be seen here: https://github.com/dmkoch/django-jsonfield/issues/189

This library still holds django-jsonfield to v1.0.3 as of django-slack-oauth v1.0.0 . Upgrading the jsonfield library would help with general Django 1.11 support.

Not sure what the impact is for Django 1.8 support but wanted to bring this issue to this library's attention.

Thank you for making this library. Deeply appreciate that we have it in the Django community.

**Comment by izdi** [comment]
Thanks for keeping track🥇 
Updated and released to PYPI.
