### ISSUE TITLE
[Alternative Request] Usage of other storage solution than cache for validating state.

### ISSUE THREAD

**Issue by avelis** [izdi/django-slack-oauth#6]
According to this old thread issue.
https://code.djangoproject.com/ticket/7639

LocMemCache is not ideal for production environments. In fact each process contains it's own cache object. So, in practice validate_state could always be false if you are running more than one thread to serve a Django application. (e.g. gunicorn)

While setting up a cache that spans across threads is the next ideal step this increases the dependencies for using the library in a production environment.

**Comment by avelis** [comment]
@izdi I can understand from a security standpoint the point of validate_state but it might easier to add a flag to disable that or update your documentation to state that you have to setup a cache service.

**Comment by izdi** [comment]
@avelis I assumed that production ready projects use a caching layer other than `LocMemCache`. So in my opinion, `cache`object uses cache backend specified in `settings.py` which eliminates need for additional documentation.

But I'll stick with you and add a check for cache backend.

**Comment by izdi** [comment]
Added proper documentation in 36178ffd740f3ec50fb31a1f34cdb0ff5dca1870

Thanks again @avelis !
